name: FirstPlugin
version: '${project.version}'
main: com.andreea.test.Main
api-version: '1.20'
commands:
  heal:
    description: healing the health of a player
  test:
  console:
  config:
  permission:
  testparticles:
    description: Test particle effect
  vanish: