name: FirstPlugin
version: '1.0-SNAPSHOT'
main: com.andreea.test.Main
api-version: '1.20'
commands:
  menu:
    description: Opens a GUI menu
  heal:
    description: healing the health of a player
  test:
  console:
  config:
  permission:
  testparticles:
    description: Test particle effect
  vanish:
  book:
  banner:
    description: Gives the player a custom-made banner
  punish:
  timePlayed:
    description: Gives the time that a player has been on the server
  message:
  reply:
  fruit:
  boost:
  cooldown:
  hologram:
  perms:
